### ISSUE TITLE
Dodać await

### ISSUE THREAD

**Issue by Miszq11** [KotletJB/piotrkowski#1]
@KotletJB dodaj await przed ctx.send(...) do obu wywołań, dla funkcji lista()

**Comment by KotletJB** [comment]
dodałem ale nie działa

**Comment by Miszq11** [comment]
kier, wstawisz dumpa?

**Comment by KotletJB** [comment]
zaraz naprawie

**Comment by KotletJB** [comment]
juz działa

**Comment by KotletJB** [comment]
`sound_path = './'`
